<?php
    /* Motion Bank ZZZZ module */
    
    /**
     *  Hook form alter.
     */
    
    function zzzz_motionbank_form_alter( &$form, &$form_state, $form_id )
    {
        
    // changes to node form for organic groups
        
        if ( $form_id == 'project_node_form' )
        {
            /*$container = array(
                    '#type' => 'fieldset',
                    '#title' => t('Project settings'),
                    '#weight' => 100,
                    '#collapsible' => TRUE,
                    '#collapsed' => TRUE,
            );
            
            foreach ( $form["#content_extra_fields"] as $k => $v )
            {
                if ( strpos( $k, 'og_' ) === 0 )
                {
                    echo $k . ' ';
                    $container[$k] = $form["#content_extra_fields"][$k];
                    unset($form["#content_extra_fields"][$k]);
                }
            }
            
            $form["#content_extra_fields"]['og_container'] = $container;
            
            var_dump( $form["#content_extra_fields"] );*/
        }
    }